repos:
-   repo: https://github.com/psf/black
    rev: 24.2.0
    hooks:
    -   id: black
        language_version: python3
        types_or: [python, jupyter]
        additional_dependencies: ["black[jupyter]"]